import pygame

questions = [
    ["A", "Chicago is a \n A: City \n B: State \n C: Country"],
    ["B", "Knowledge management systems are called expert systems because they ____. \n A.	provide job-related information to users at all levels of a company \n B.	simulate human reasoning by combining a knowledge base and inference rules that determine how the knowledge is applied \n C.	process data generated by day-to-day business operations \n D.	include e-mail, voice mail, fax, video conferencing, word processing, automated calendars, database management, spreadsheets, and high-speed Internet access"],
    ["C", " 4.	A ____, or requirements model, describes the information that a system must provide.\n  \n A.	process model\n B.	data model\n C.	business model\n D.	network model"]
]

# plays the sound

pygame.mixer.init()
pygame.mixer.music.load("alarm.mp3")
pygame.mixer.music.play(loops=-1)

NotDone = 1
while NotDone:
    for item in questions:
        print(item[1])
        tries = 0
        while tries < 3:
            user_ans = input("Answer : ")

            if item[0] == user_ans.upper():
                tries = 4

            tries += 1
    NotDone = 0
